### PR TITLE
typescript definition files

### PR DESCRIPTION
**Pull request by aalpgiray**
I am kinda new at this. If you have any rules or guide for contributors, please share.

### CODE REVIEW

**Comment by salvoravida** [comment]
i think easy-peasy createStore should extend redux Store type, and redux-first-history just  use store:Store?

no?

**Comment by aalpgiray** [comment]
Perhaps you are right. I am on it.

**Comment by salvoravida** [comment]
ok,
1) fix : declare function createReduxHistory(store: Store): History;
2) remove type-zoo/types  dep.

then i will merge this pr.

**Comment by aalpgiray** [comment]
Ok, I removed `type-zoo` and replaced `Overwrite<Store, any> `with `Store` .

**Comment by salvoravida** [comment]
@aalpgiray merged!

**Comment by aalpgiray** [comment]
Thanks

**Pull request merged**
